###
GET  http://localhost:3100/tasks/consult-tasks/1

###
POST  http://localhost:3100/tasks/save-task
Content-Type: application/json

{
  "id_user": 1,
  "id_folders": 1,
  "title": "Test",
  "description": "Test: LOREM IPSUM DOLOR SIT AMET",
  "status": "pendiente",
  "priority": "medio",
  "due_date": "2022-01-01"
}


###
PUT  http://localhost:3100/tasks/update-task/1
Content-Type: application/json

{
  "id": 1,
  "title": "Test",
  "description": "Test: LOREM IPSUM DOLOR SIT AMET",
  "status": "pendiente",
  "priority": "medio",
  "due_date": "2022-01-01"
}


###
DELETE  http://localhost:3100/tasks/delete-task/1